insert into cuisine (id, name) values(1, 'Italian');
insert into cuisine (id, name) values(2, 'Brazilian');
insert into restaurant (name, freight_rate, cuisine_id) values ('Pecorino', 16.9, 1);
insert into restaurant (name, freight_rate, cuisine_id) values ('Compadre', 30, 2);
insert into state (id, name) values (1, 'Minas Gerais');
insert into state (id, name) values (2, 'Bahia');
insert into state (id, name) values (3, 'Pernambuco');
insert into city (id, name, state_id) values (1, 'Belo Horizonte', 1);
insert into city (id, name, state_id) values (2, 'Salvador', 2);
insert into city (id, name, state_id) values (3, 'Recife', 3);
insert into payment_method (id, description) values (1, 'Credit Card');
insert into payment_method (id, description) values (2, 'Debit Card');
insert into payment_method (id, description) values (3, 'Money');
insert into permission (id, name, description) values (1, 'CONSULT', 'Allows you consult cuisines');
insert into permission (id, name, description) values (2, 'EDIT', 'Allows you to edit cuisines');
insert into restaurant_payment_method (restaurant_id, payment_method_id) values (1,1), (1,2), (1,3), (2,3);